name: CI Build-Test-LuaCov

on:
  push:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ci-runner
    image: ngc717/defold-ci-env:latest
    steps:
      - name: Setup node.js
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build game
        run : |
          echo "running bob.jar"
          java -jar bob.jar --debug build

      - name: Start dmengine
        run : |
          echo "Starting dmengine_headless"
          ./dmengine_headless

      - name: Upload TestCov
        uses: codecov/codecov-action@v3